const FreddyMenu = {
    frames : [
        "../assets/menu/1.png",
        "../assets/menu/1.png",
        "../assets/menu/1.png",
        "../assets/menu/1.png",
        "../assets/menu/1.png",
        "../assets/menu/1.png",
        "../assets/menu/1.png",
        "../assets/menu/1.png",
        "../assets/menu/1.png",
        "../assets/menu/1.png",
        "../assets/menu/2.png",
        "../assets/menu/2.png",
        "../assets/menu/1.png",
        "../assets/menu/1.png",
        "../assets/menu/1.png",
        "../assets/menu/1.png",
        "../assets/menu/1.png",
        "../assets/menu/1.png",
        "../assets/menu/1.png",
        "../assets/menu/1.png",
        "../assets/menu/1.png",
        "../assets/menu/1.png",
        "../assets/menu/1.png",
        "../assets/menu/1.png",
        "../assets/menu/1.png",
        "../assets/menu/1.png",
        "../assets/menu/1.png",
        "../assets/menu/1.png",
        "../assets/menu/1.png",
        "../assets/menu/4.png",
        "../assets/menu/4.png",
        "../assets/menu/1.png",
        "../assets/menu/1.png",
        "../assets/menu/1.png",
        "../assets/menu/4.png",
        "../assets/menu/4.png",
        "../assets/menu/1.png",
        "../assets/menu/1.png",
        "../assets/menu/1.png",
        "../assets/menu/1.png",
        "../assets/menu/1.png",
        "../assets/menu/1.png",
        "../assets/menu/1.png",
        "../assets/menu/3.png",
        "../assets/menu/3.png",
        "../assets/menu/1.png",
        "../assets/menu/1.png",
    ],
    fps: 15
};

const noiseMenu = {
    frames : [
        "../assets/menu/staticNoise1.png",
        "../assets/menu/staticNoise2.png",
        "../assets/menu/staticNoise3.png",
        "../assets/menu/staticNoise4.png",
        "../assets/menu/staticNoise5.png",
        "../assets/menu/staticNoise6.png",
        "../assets/menu/staticNoise7.png",
        "../assets/menu/staticNoise8.png",
    ],
    fps:30
};

const whiteMenu = {
    frames : [
        "../assets/menu/whiteNoise1.png",
        "../assets/menu/whiteNoise2.png",
        "../assets/menu/empty.png",
        "../assets/menu/empty.png",
        "../assets/menu/empty.png",
        "../assets/menu/empty.png",
        "../assets/menu/empty.png",
        "../assets/menu/empty.png",
        "../assets/menu/whiteNoise2.png",
        "../assets/menu/whiteNoise3.png",
        "../assets/menu/empty.png",
        "../assets/menu/empty.png",
        "../assets/menu/whiteNoise4.png",
        "../assets/menu/whiteNoise5.png",
        "../assets/menu/empty.png",
        "../assets/menu/empty.png",
        "../assets/menu/empty.png",
        "../assets/menu/whiteNoise6.png",
        "../assets/menu/whiteNoise7.png",
        "../assets/menu/empty.png",
        "../assets/menu/whiteNoise7.png",
        "../assets/menu/whiteNoise8.png",
        "../assets/menu/whiteNoise9.png",
        "../assets/menu/empty.png",
        "../assets/menu/empty.png",
        "../assets/menu/whiteNoise10.png",
        "../assets/menu/whiteNoise11.png",
        "../assets/menu/whiteNoise12.png",
        "../assets/menu/empty.png",
        "../assets/menu/empty.png",
        "../assets/menu/empty.png",
        "../assets/menu/empty.png",
        "../assets/menu/whiteNoise13.png",
        "../assets/menu/whiteNoise14.png",
        "../assets/menu/empty.png",
        "../assets/menu/empty.png",
        "../assets/menu/empty.png",
        "../assets/menu/empty.png",
        "../assets/menu/empty.png",
        "../assets/menu/empty.png",
        "../assets/menu/empty.png",
        "../assets/menu/empty.png",
        "../assets/menu/empty.png",
        "../assets/menu/whiteNoise16.png",
    ],
    fps : 15
}

